"""create inventory tables

Revision ID: 350a6529f67d
Revises: 
Create Date: 2026-10-03 01:06:13.205784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '350a6529f67d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('circuit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('capacity_kva', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.CheckConstraint('capacity_kva > 0', name=op.f('ck_circuit_capacity_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_circuit')),
    sa.UniqueConstraint('code', name=op.f('uq_circuit_code'))
    )
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('acorn_group', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer')),
    sa.UniqueConstraint('code', name=op.f('uq_customer_code'))
    )
    op.create_table('contract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('tariff_type', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.CheckConstraint("tariff_type IN ('standard', 'dynamic')", name=op.f('ck_contract_tariff_type_valid')),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('fk_contract_customer_id_customer')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contract')),
    sa.UniqueConstraint('code', name=op.f('uq_contract_code'))
    )
    op.create_index(op.f('ix_contract_customer_id'), 'contract', ['customer_id'], unique=False)
    op.create_table('transformer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('circuit_id', sa.Integer(), nullable=False),
    sa.Column('capacity_kva', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.CheckConstraint('capacity_kva > 0', name=op.f('ck_transformer_capacity_positive')),
    sa.ForeignKeyConstraint(['circuit_id'], ['circuit.id'], name=op.f('fk_transformer_circuit_id_circuit')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transformer')),
    sa.UniqueConstraint('code', name=op.f('uq_transformer_code'))
    )
    op.create_index(op.f('ix_transformer_circuit_id'), 'transformer', ['circuit_id'], unique=False)
    op.create_table('meter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lclid', sa.String(length=20), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('transformer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('fk_meter_customer_id_customer')),
    sa.ForeignKeyConstraint(['transformer_id'], ['transformer.id'], name=op.f('fk_meter_transformer_id_transformer')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meter')),
    sa.UniqueConstraint('lclid', name=op.f('uq_meter_lclid'))
    )
    op.create_index(op.f('ix_meter_customer_id'), 'meter', ['customer_id'], unique=False)
    op.create_index(op.f('ix_meter_transformer_id'), 'meter', ['transformer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meter_transformer_id'), table_name='meter')
    op.drop_index(op.f('ix_meter_customer_id'), table_name='meter')
    op.drop_table('meter')
    op.drop_index(op.f('ix_transformer_circuit_id'), table_name='transformer')
    op.drop_table('transformer')
    op.drop_index(op.f('ix_contract_customer_id'), table_name='contract')
    op.drop_table('contract')
    op.drop_table('customer')
    op.drop_table('circuit')
    # ### end Alembic commands ###
