"""add acorn_grouped to customer

Revision ID: cb10f7277f53
Revises: 350a6529f67d
Create Date: 2026-10-03 16:31:09.141652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb10f7277f53'
down_revision: Union[str, Sequence[str], None] = '350a6529f67d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('acorn_grouped', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###
    op.create_check_constraint(
        'acorn_grouped_valid',
        'customer',
        "acorn_grouped IN ('Affluent', 'Comfortable', 'Adversity', 'Unknown')",
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_customer_acorn_grouped_valid'), 'customer', type_='check')
    op.drop_column('customer', 'acorn_grouped')
    # ### end Alembic commands ###
